### ISSUE TITLE
multiprecision models

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/dust#142]
We might need to deal with this for use with the GPU. Some way of creating a model that can switch types between `double` and `float` at creation

**Comment by johnlees** [comment]
I think this is already done?

**Comment by richfitz** [comment]
not in dust, just in odin.dust, and only at compile time

**Comment by johnlees** [comment]
Ah right I remember, this is where one wants two models simultaneously in the package: a double model for the CPU and a float model for the GPU

**Comment by richfitz** [comment]
We've got a strategy for this now with sircovid at least
