### ISSUE TITLE
Support for negative binomial distribution

### ISSUE THREAD

**Issue by kgaythorpe** [mrc-ide/dust#171]
It would be fantastic to be able to use the negative binomial distribution (particularly for defining likelihoods)

**Comment by richfitz** [comment]
We do support negative binomial densities for likelihoods (this is only an issue if using a compiled comparison function; most models will start implementing that side in R for now). Do you need random variates too?

If you do need variates, the parametrisation we are using for the densities is here: https://github.com/mrc-ide/dust/blob/4093f4dd7c7f0d29224dc674c6de5822074e6ff5/inst/include/dust/densities.hpp#L54-L71 is that similar enough to what you need?

**Comment by richfitz** [comment]
The R/C API has rnbinom in terms of `size, prob` so we probably need to update this...
