### ISSUE TITLE
Remove Rcpp, or at least make it optional

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/dust#22]
The compilation times, which were one of several concerns, are even worse than I remember. Once we have things stable and a decent suite of tests it will become easier and safer to remove it and replace with a plain C++ interface and a C interface for R.

The big challenge will be the marshalling of data from R, the bit like

```
template <>
parallel::init_t dust_data<parallel>(Rcpp::List data) {
  double sd = Rcpp::as<double>(data["sd"]);
  return parallel::init_t{sd};
}
```

because we need to create an object of type `parallel::init_t` and that will contain arbitrary C++ types, it's a challenge to do without a bit more work.

**Comment by richfitz** [comment]
https://github.com/r-lib/cpp11 - this looks very promising

**Comment by johnlees** [comment]
Definitely, this looks similar to the one I use with python, which is a lot faster to compile than Rcpp: https://github.com/pybind/pybind11
