### ISSUE TITLE
Better RNG state handling

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/dust#87]
Global RNG state is nice because it updates everywhere. We don't have that so we should think about it more.

Something like 

```
dust_rng_state()
```

as a free function is needed to check an initial state. Options should be a raw vector (the results of getting the rng state from a dust object), an integer (set seed as currently) or `NULL` in which case follow the idea in #85

**Comment by johnlees** [comment]
Agree that this is a neat solution. If we are able to take the state of the 0 index particle I think that that would be enough, as then you could reapply jump for the number of particles then needed

**Comment by richfitz** [comment]
yeah, this seems easier to implement and defensible
