### ISSUE TITLE
Vignette needs updating

### ISSUE THREAD

**Issue by richfitz** [mrc-ide/dust#98]
In changing the seed behaviour in #88 we broke the breakage in the vignette: https://mrc-ide.github.io/dust/articles/dust.html#reset-the-model

**Comment by johnlees** [comment]
Other collected thoughts:

- [ ] Noting that no underscores can be used in file/model names
- [ ] How to enable openmp on OS X (either through homebrew and gcc, or `brew install libomp` and compiler flags `-Xpreprocessor -fopenmp -lomp`)
